Hinzufügen der Funktion Skript zu verstecken
symcon/Aktivliste pull request #12
Opened 2023-06-28 09:04 UTC by Sunnyka98

Hinzufügen der Funktion das Skript für das simultanen Ausschalten zu verstecken. 

close https://github.com/symcon/modules/issues/237

2023-09-21 07:48 UTC, paresy commented
Ich würde dies umdrehen und eine Property Namens "TurnOffAction" nehmen, welche standardmäßig auf "true" ist. Dann ist der Name der Checkbox in der Konfiguration klarer, als das "Read only".

2023-09-21 07:49 UTC, paresy requested changes
Siehe Kommentar

2024-03-26 10:16 UTC, paresy commented
Magst du die Konflikte korrigieren? Die sind leider durch das umbenennen passiert. (Am einfachsten ist es einfach die Umbenennung nachzuziehen. Dann müssten die Konflikte weg sein)

2024-04-05 08:07 UTC, Sunnyka98 commented
wurde Local getestet : 
```
PHPUnit 11.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.15
Configuration: C:\ProgramData\Symcon\modules\Aktivliste\tests\phpunit.xml

...............                                                   15 / 15 (100%)

Time: 00:00.007, Memory: 24.00 MB

OK (15 tests, 350 assertions)
```

2024-06-10 07:19 UTC, merged